### ISSUE TITLE
Missing plot_link relation relType

### ISSUE THREAD

**Issue by sjtuprog** [tommasoc80/EventStoryLine#1]
There are some plot_links which were not fully annotated.

See the list below:
13_4ecbplus.xml.xml r_id=  99542
19_9ecbplus.xml.xml r_id=  96260
3_5ecbplus.xml.xml r_id=  96640
3_6ecbplus.xml.xml r_id=  96651
30_12ecbplus.xml.xml r_id=  213574
32_3ecbplus.xml.xml r_id=  208407
33_7ecbplus.xml.xml r_id=  213471
35_4ecbplus.xml.xml r_id=  215469
37_11ecbplus.xml.xml r_id=  90985
37_13ecbplus.xml.xml r_id=  91002
37_14ecbplus.xml.xml r_id=  91013
37_1ecbplus.xml.xml r_id=  91031
37_2ecbplus.xml.xml r_id=  91056
41_6ecbplus.xml.xml r_id=  104582

**Comment by tommasoc80** [comment]
The missing PLOT_LINK refers to version 0.9.
Experiments/Baselines reported on the EventStory workshop paper "[The Event StoryLine Corpus](http://aclweb.org/anthology/W/W17/W17-2711.pdf)" use version 0.9 as it is, including incomplete plot links.
All issues concerning incomplete PLOT_LINK, timex normalisation etc. have been solved in version 1.0.
To compare the results of new systems with the baselines in The Event StoryLine Corpus use version 0.9 as it is - including incomplete data. For new experiments use version 1.0.
