### ISSUE TITLE
The number of PLOT LINK relation does not correspond to the number that paper illustrated

### ISSUE THREAD

**Issue by taojingcong** [tommasoc80/EventStoryLine#11]
In ./evaluation_format/full_corpus/v0.9/event_mentions_extended/, there exists 5,602 PLOT LINK relations, which should be 5,519 that illustrated in _The Event StoryLine Corpus: A New Benchmark for Causal and Temporal Relation Extraction_.

In ./evaluation_format/full_corpus/v0.9/coref_chain/, there exists 2,243 PLOT LINK relations, which should be 2,265 illustrated in the same paper.

**Comment by tommasoc80** [comment]
These are typos - sorry.
