### ISSUE TITLE
Empty folder

### ISSUE THREAD

**Issue by Laityzk** [tommasoc80/EventStoryLine#5]
I found this folder(evaluation_format/full_corpus/v1.0/event_mentions_extended/5) is empty, is there any problem?

**Comment by tommasoc80** [comment]
No, that's correct. No plot link has been annotated in those files.

**Comment by Laityzk** [comment]
Thank you for response!
Can I understand in this way,
For the causal relations in 5_1ecbplus, I only need to use <PLOT_LINK> in 5_1ecbplus.xml.xml, and do not consider the relations in 5_1ecbplus.tab
