### ISSUE TITLE
Causal and Corefer relationship appear at the same time

### ISSUE THREAD

**Issue by Laityzk** [tommasoc80/EventStoryLine#6]
I found some trigger pairs have causal and corefer relationship at the same time，how to understand this phenomenon?
e.g. 
evaluation_format\full_corpus\v1.0\coref_chain\3\3_6ecbplus.tab
"56 38_39_40 90 175_176 95_96	56 38_39_40 90 175_176 95_96	PRECONDITION"

**Comment by tommasoc80** [comment]
These are likely annotation errors in the coreference layer from ECB+.

Check:  annotated_data/v1.0/3/3_6ecbplus.xml.xml 
*** tokens ****
<token t_id="85" sentence="4" number="15">on</token>
<token t_id="86" sentence="4" number="16">Monday</token>
<token t_id="87" sentence="4" number="17">morning</token>
<token t_id="88" sentence="4" number="18">and</token>
<token t_id="89" sentence="4" number="19">then</token>
<token t_id="90" sentence="4" number="20">escaped</token>
<token t_id="91" sentence="4" number="21">from</token>
<token t_id="92" sentence="4" number="22">the</token>
<token t_id="93" sentence="4" number="23">vehicle</token>
<token t_id="94" sentence="4" number="24">and</token>
<token t_id="95" sentence="4" number="25">took</token>
<token t_id="96" sentence="4" number="26">off</token>
<token t_id="97" sentence="4" number="27">on</token>
<token t_id="98" sentence="4" number="28">foot</token>

*** events ****
<ACTION_OCCURRENCE m_id="7" climaxEvent="FALSE" comment=""  >
<token_anchor t_id="90"/>
<ACTION_OCCURRENCE m_id="8" climaxEvent="FALSE" comment=""  >
<token_anchor t_id="95"/>
<token_anchor t_id="96"/>

**** PLOT LINK ****
<PLOT_LINK r_id="234877" >
<source m_id="7" /> 
<target m_id="8" />

**** COREFERENCE - /ECB+_LREC2014/ECB+/3/3_6ecbplus.xml ****

<CROSS_DOC_COREF r_id="22197" note="ACT16190399378875259" >
  <source m_id="12" />
  <source m_id="10" />
  <source m_id="14" />
  <source m_id="24" />
  <source m_id="15" />
  <target m_id="65" />

 <source m_id="10" /> (<token_anchor t_id="90"/> "escaped") and <source m_id="24" /> (<token_anchor t_id="95"/> <token_anchor t_id="96"/> "took off") are marked as coreferential. However, given their context of occurrence and the likely temporal relations connecting the two, coreference does not seem valid. 

Dropping such cases seems the best option.
